version: '3.6'

services:
  app:
    build:
      context: .
      target: release
    volumes:
      - .:/app
    command: sleep infinity

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db:/docker-entrypoint-initdb.d
